version: 2.1

jobs:
  run_test:
    macos:
      xcode: 12.5.1
    environment:
      FASTLANE_LANE: build_and_test
    steps:
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: bundle install
      - run:
          name: run and test
          command: bundle exec fastlane $FASTLANE_LANE