
jobs:
  build-and-test:
    macos:
      xcode: 11.3.0
    steps:
      ...
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: WebTests
steps:
      - run: fastlane scan
version: 2.1
jobs:
  test:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: fastlane scan
  deploy:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - deploy:
          name: Deploy
          command: fastlane release_appstore
workflows:
  test_release:
    jobs:
      - test
      - deploy:
          requires:
            test
          filters:
            branches:
              only: release
